version: "3"
services:
  testdb:
    image: postgres
    restart: always
    container_name: tinkoff-broker-stats-db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_DB=postgres"
    ports:
      - 44219:5432