// Code generated by ifacemaker. DO NOT EDIT.

package tinkoff

import (
	"context"
)

// API interface for tinkoff client
type API interface {
	GetPortfolio(ctx context.Context, accountID string) (Portfolio, error)
	GetAccounts(ctx context.Context) ([]Account, error)
}
